routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Whoops\Run;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/','FrontController@index');
Route::get('/daftar-sekolah','FrontController@daftarSekolah')->name('daftarsekolah');
Route::post('/daftar-sekolah','FrontController@storeDaftarSekolah')->name('daftarsekolah.store');
Route::get('/jobseeker/login','Jobseeker\LoginController@index')->name('login');
Route::post('/login/process','Jobseeker\LoginController@process')->name('login.process');
Route::post('/register','Jobseeker\RegisterController@register')->name('register');

Route::group(['prefix' => 'jobseeker', 'middleware' => 'students'], function(){
    Route::get('/jobvacancy','FrontController@jobVacancy')->name('jobvacancy');
    Route::get('/apply/{id}','FrontController@apply')->name('apply');
    Route::get('/informasi-lamaran','FrontController@informationApply')->name('informasi');
    Route::get('/profile','FrontController@profile')->name('profile.student');
    Route::post('/profile/{id}','FrontController@profileUpdate')->name('jobseeker.edit');
    Route::post('/logout','Jobseeker\LoginController@logout')->name('logout');
    Route::get('/postingan','FrontController@postingan')->name('postingan.index');
});

Route::group(['prefix' => 'admin'], function(){
    Route::get('/login','Auth\LoginController@loginAdmin')->name('login.admin');
    Route::post('/login','Auth\LoginController@loginProcessAdmin')->name('loginprocess.admin');
    Route::group(['middleware' => 'auth'], function(){
        Route::get('/dashboard','HomeController@index')->name('home.admin');
        Route::resource('company','CompanyController')->except(['show']);
        Route::resource('setting','SettingController')->except(['show']);
        Route::resource('alumni','StudentController')->except(['show']);
        Route::resource('admin','AdminController');
        Route::get('/adminsekolah/acc/{id}','AdminController@acc')->name('admin.acc');
        Route::get('/adminsekolah/reject/{id}','AdminController@reject')->name('admin.reject');
        Route::get('/adminsekolah/bukti/{id}','AdminController@bukti')->name('admin.bukti');
        Route::resource('bursakerja','JobVacancyController')->except(['show']);
        Route::get('/pelamar/{id}','JobVacancyController@pelamar')->name('pelamar');
        Route::post('/logout','Auth\LoginController@logout')->name('logout.admin');
        Route::get('/profile','HomeController@profile')->name('profile');
        Route::put('/profile/{id}','HomeController@profileUpdate')->name('profile.update');
        Route::get('/apply/accepted/{id}','JobVacancyController@accepted');
        Route::get('/apply/rejected/{id}','JobVacancyController@rejected');
        Route::post('/post','JobVacancyController@postStore')->name('post.store');
        Route::get('/apply/test/accpeted/{id}','JobVacancyController@testAccepted')->name('test.accepted');
        Route::get('/apply/test/rejected/{id}','JobVacancyController@testRejected')->name('test.rejected');
        Route::get('/apply/wawancara/accpeted/{id}','JobVacancyController@wawancaraAccepted')->name('wawancara.accepted');
        Route::get('/apply/wawancara/rejected/{id}','JobVacancyController@wawancaraRejected')->name('wawancara.rejected');
    } );
});

resources/views/adminsekolah/create.blade.php
@extends('layouts.admin.master')
@section('title','Tambah Admin Sekolah')
@section('css')
<link rel="stylesheet" href="{{ asset('select2/css/select2.min.css') }}">
@stop
@section('content') 
    <div class="row">
        <div class="col-md-6">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                  <h6 class="m-0 font-weight-bold text-primary"><a href="{{ route('alumni.index') }}" class="btn btn-circle"><i class="fa fa-arrow-left"></i></a> Data Admin</h6>
                </div>
                <div class="card-body">
                    @if (Session::has('message'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ Session::get('message') }}
                        @php 
                            Session::forget('message')
                        @endphp
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>                        
                    @endif
                    <form action="{{ route('admin.store') }}" method="post">
                        @csrf
                        <div class="form-group row">
                           <div class="col-md-6 mb-3">
                                <label for="name">Nama</label>
                                <input type="text" class="form-control form-control-sm @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}">
                                @error('name')
                                    <div class="invalid-feedback" role="alert">
                                        <span>{{ $message }}</span>
                                    </div>
                                @enderror
                           </div>
                            <div class="col-md-6">
                                <label for="email">Email</label>
                                <input type="text" class="form-control form-control-sm @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}">
                                @error('email')
                                    <div class="invalid-feedback" role="alert">
                                        <span>{{ $message }}</span>
                                    </div>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-6">
                                <label for="email">No. Tlp</label>
                                <input type="text" class="form-control form-control-sm @error('phonenumber') is-invalid @enderror" name="phonenumber" value="{{ old('phonenumber') }}">
                                @error('phonenumber')
                                    <div class="invalid-feedback" role="alert">
                                        <span>{{ $message }}</span>
                                    </div>
                                @enderror
                            </div>
                            <div class="col-md-6">
                                <label for="password">Password</label>
                                <input type="password" class="form-control form-control-sm @error('password') is-invalid @enderror" name="password" value="{{ old('passowrd') }}">
                                @error('passowrd')
                                    <div class="invalid-feedback" role="alert">
                                        <span>{{ $message }}</span>
                                    </div>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-12">
                                <label for="sekolah">Sekolah</label>
                                <select name="school_id" id="school_name" class="form-control form-control-sm @error('school_id') is-invalid @enderror ">
                                    <option value="">Pilih Sekolah</option>
                                    @foreach ($school as $item)
                                        <option value="{{ $item->id }}">{{ $item->sekolah }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <button class="btn btn-primary btn-sm">Simpan</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('js')
<script src="{{ asset('select2/js/select2.min.js') }}"></script>
<script>
    $(document).ready(function(){
        $('#school_name').select2({
            width: 'resolve'
        });
    });
</script>
@stop

resources/views/adminsekolah/edit.blade.php
@extends('layouts.admin.master')
@section('title','Edit - '.$admin->name)
@section('css')
<link rel="stylesheet" href="{{ asset('select2/css/select2.min.css') }}">
@stop
@section('content') 
    <div class="row">
        <div class="col-md-6">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                  <h6 class="m-0 font-weight-bold text-primary"><a href="{{ route('admin.index') }}" class="btn btn-circle"><i class="fa fa-arrow-left"></i></a> Edit - {{ $admin->name }}</h6>
                </div>
                <div class="card-body">
                    @if (Session::has('message'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ Session::get('message') }}
                        @php 
                            Session::forget('message')
                        @endphp
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>                        
                    @endif
                    <form action="{{ route('admin.update', $admin->id) }}" method="post">
                        @csrf
                        @method('put')
                        <div class="form-group row">
                           <div class="col-md-6 mb-3">
                                <label for="name">Nama</label>
                                <input type="text" class="form-control form-control-sm @error('name') is-invalid @enderror" name="name" value="{{ $admin->name }}">
                                @error('name')
                                    <div class="invalid-feedback" role="alert">
                                        <span>{{ $message }}</span>
                                    </div>
                                @enderror
                           </div>
                            <div class="col-md-6">
                                <label for="email">Email</label>
                                <input type="text" class="form-control form-control-sm @error('email') is-invalid @enderror" name="email" value="{{ $admin->email }}">
                                @error('email')
                                    <div class="invalid-feedback" role="alert">
                                        <span>{{ $message }}</span>
                                    </div>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-6">
                                <label for="email">No. Tlp</label>
                                <input type="text" class="form-control form-control-sm @error('phonenumber') is-invalid @enderror" name="phonenumber" value="{{ $admin->phonenumber }}">
                                @error('phonenumber')
                                    <div class="invalid-feedback" role="alert">
                                        <span>{{ $message }}</span>
                                    </div>
                                @enderror
                            </div>
                            <div class="col-md-6">
                                <label for="password">Password</label>
                                <input type="password" class="form-control form-control-sm @error('password') is-invalid @enderror" name="password" value="{{ old('passowrd') }}">
                                <small class="text-muted">Kosongkan bila tidak ingin merubah password</small>
                                @error('passowrd')
                                    <div class="invalid-feedback" role="alert">
                                        <span>{{ $message }}</span>
                                    </div>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-12">
                                <label for="sekolah">Sekolah</label>
                                <select name="school_id" id="school_name" class="form-control form-control-sm @error('school_id') is-invalid @enderror ">
                                    <option value="">Pilih Sekolah</option>
                                    @foreach ($school as $item)
                                        <option value="{{ $item->id }}" {{ $admin->school_id == $item->id ? 'selected' : '' }}>{{ $item->sekolah }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <button class="btn btn-primary btn-sm">Simpan</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('js')
<script src="{{ asset('select2/js/select2.min.js') }}"></script>
<script>
    $(document).ready(function(){
        $('#school_name').select2({
            width: 'resolve'
        });
    });
</script>
@stop

resources/views/adminsekolah/index.blade.php
@extends('layouts.admin.master')
@section('title','Daftar Admin Sekolah')
@section('content')
<div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Daftar Admin Sekolah</h6>
    </div>
    <div class="card-body">
        <div class="mb-3">
            <a href="{{ route('admin.create') }}" class="btn btn-success btn-sm">Tambah Data</a>
        </div>
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th width="180">Nama</th>
                        <th>Email</th>
                        <th>No Telp.</th>
                        <th>Sekolah</th>
                        <th>Alamat</th>
                        <th width="100">#</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($admin as $item)
                        <tr>
                            <td>{{ $item->name }}</td>
                            <td>{{ $item->email }}</td>
                            <td>{{ $item->phonenumber }}</td>
                            <td>{{ $item->sekolah->sekolah }}</td>
                            <td>{{ $item->sekolah->alamat_jalan }}, {{ $item->sekolah->kecamatan }}, {{ $item->sekolah->kabupaten_kota }}, {{ $item->sekolah->propinsi }}</td>
                            <td>
                                <a href="{{ route('admin.edit', $item->id) }}" class="btn btn-warning btn-sm btn-circle"><i class="fa fa-edit"></i></a>
                                <a href="{{ route('admin.destroy', $item->id) }}" class="btn btn-danger btn-sm hapus btn-circle"><i class="fa fa-trash"></i></a>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="7">Tidak ada data</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
        {!! $admin->links() !!}
    </div>
</div>
@endsection
@section('js')
    <script src="{{ asset('vendor/sweetalert/sweetalert.min.js') }}"></script>
    <script>
        $(document).ready(function(){
            $('.hapus').on('click', function(){
                swal({
                    title: "Apa anda yakin?",
                    text: "Data yang dihapus tidak dapat dikembalikan",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true,
                })
                .then((willDelete) => {
                    if(willDelete) {
                        $.ajax({
                            url: $(this).attr('href'),
                            type: "DELETE",
                            data: {
                                "_token": "{{ csrf_token() }}"
                            },
                            success:function(){
                                swal("Data berhasil dihapus", {
                                    icon: "success",
                                }).then((willDelete) => {
                                    window.location="{{ route('admin.index') }}"
                                });
                            }
                        });
                    } else {
                        swal("Data aman");
                    }
                });

                return false;
            });
        }); 
    </script>
@endsection