routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Whoops\Run;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/','FrontController@index');
Route::get('/daftar-sekolah','FrontController@daftarSekolah')->name('daftarsekolah');
Route::post('/daftar-sekolah','FrontController@storeDaftarSekolah')->name('daftarsekolah.store');
Route::get('/jobseeker/login','Jobseeker\LoginController@index')->name('login');
Route::post('/login/process','Jobseeker\LoginController@process')->name('login.process');
Route::post('/register','Jobseeker\RegisterController@register')->name('register');

Route::group(['prefix' => 'jobseeker', 'middleware' => 'students'], function(){
    Route::get('/jobvacancy','FrontController@jobVacancy')->name('jobvacancy');
    Route::get('/apply/{id}','FrontController@apply')->name('apply');
    Route::get('/informasi-lamaran','FrontController@informationApply')->name('informasi');
    Route::get('/profile','FrontController@profile')->name('profile.student');
    Route::post('/profile/{id}','FrontController@profileUpdate')->name('jobseeker.edit');
    Route::post('/logout','Jobseeker\LoginController@logout')->name('logout');
    Route::get('/postingan','FrontController@postingan')->name('postingan.index');
});

Route::group(['prefix' => 'admin'], function(){
    Route::get('/login','Auth\LoginController@loginAdmin')->name('login.admin');
    Route::post('/login','Auth\LoginController@loginProcessAdmin')->name('loginprocess.admin');
    Route::group(['middleware' => 'auth'], function(){
        Route::get('/dashboard','HomeController@index')->name('home.admin');
        Route::resource('company','CompanyController')->except(['show']);
        Route::resource('setting','SettingController')->except(['show']);
        Route::resource('alumni','StudentController')->except(['show']);
        Route::resource('admin','AdminController');
        Route::get('/adminsekolah/acc/{id}','AdminController@acc')->name('admin.acc');
        Route::get('/adminsekolah/reject/{id}','AdminController@reject')->name('admin.reject');
        Route::get('/adminsekolah/bukti/{id}','AdminController@bukti')->name('admin.bukti');
        Route::resource('bursakerja','JobVacancyController')->except(['show']);
        Route::get('/pelamar/{id}','JobVacancyController@pelamar')->name('pelamar');
        Route::post('/logout','Auth\LoginController@logout')->name('logout.admin');
        Route::get('/profile','HomeController@profile')->name('profile');
        Route::put('/profile/{id}','HomeController@profileUpdate')->name('profile.update');
        Route::get('/apply/accepted/{id}','JobVacancyController@accepted');
        Route::get('/apply/rejected/{id}','JobVacancyController@rejected');
        Route::post('/post','JobVacancyController@postStore')->name('post.store');
        Route::get('/apply/test/accpeted/{id}','JobVacancyController@testAccepted')->name('test.accepted');
        Route::get('/apply/test/rejected/{id}','JobVacancyController@testRejected')->name('test.rejected');
        Route::get('/apply/wawancara/accpeted/{id}','JobVacancyController@wawancaraAccepted')->name('wawancara.accepted');
        Route::get('/apply/wawancara/rejected/{id}','JobVacancyController@wawancaraRejected')->name('wawancara.rejected');
    } );
});

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\School;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class Student extends Authenticatable
{
    use Notifiable;
    protected $guarded = [];
    // protected $primaryKey = 'sekolah_id';
    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = bcrypt($value);
    }
    public function sekolah()
    {
        return $this->belongsTo(School::class, 'school_id');
    }
    public function apply()
    {
        return $this->hasMany(Apply::class);
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Student;
use App\School;
use App\User;

class StudentController extends Controller
{
    public function index()
    {
        
        $students = Student::with('sekolah');
        $user = User::with('sekolah')->findOrFail(auth()->user()->id);
        if (auth()->user()->level == 1) {
            $students =$students->where('school_id',$user->sekolah->id);
        }
        // return response()->json($students);
        $students = $students->orderBy('nisn','ASC')->paginate(10);

        return view('student.index',compact('students'));
    }

    public function create()
    {
        $sekolah = School::select('id','sekolah')->get();
        $getSekolah = User::with('sekolah')->findOrFail(auth()->user()->id);
        // dd($getSekolah);
        return view('student.create',compact('sekolah','getSekolah'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'nisn'              => 'required|numeric|unique:students|min:10',
            'name'              => 'required|string',
            'gender'            => 'required|string',
            'place_of_birth'    => 'required|string',
            'date_of_birth'     => 'required|date',
            'address'           => 'required|string',
            'email'             => 'required|email',
            'npsn'              => 'required|string',
            'cv'                => 'nullable|mimes:doc,docx,pdf|max:1024',
            'photo'                => 'nullable|mimes:png,jpg,jpeg|max:1024',
        ]);

        // $password = bcrypt($request->nisn);

        $cv = '';
        $photo = '';

        if ($request->hasFile('cv')) {
            $fileCv = $request->file('cv');
            $cv = rand().'.'.$fileCv->getClientOriginalExtension();
            $fileCv->storeAs('/public/cv',$cv);
        }

        if ($request->hasFile('photo')) {
            $filePhoto = $request->file('photo');
            $photo = rand().'.'.$filePhoto->getClientOriginalExtension();
            $filePhoto->storeAs('/public/photo',$photo);
        }

        Student::create([
            'nisn'              => $request->nisn,
            'name'              => $request->name,
            'gender'            => $request->gender,
            'place_of_birth'    => $request->place_of_birth,
            'date_of_birth'     => $request->date_of_birth,
            'address'           => $request->address,
            'email'             => $request->email,
            'password'          => $request->nisn,
            'school_id'              => $request->npsn,
            'cv'                => $cv,
            'photo'             => $photo
        ]);

        return back()->with('message','Berhasil menambahkan data');
    }

    public function edit($id)
    {
        $sekolah = School::select('id','sekolah')->get();
        $student = Student::findOrFail($id);

        // dd($student);
        return view('student.edit',compact('student','sekolah'));
    }

    public function update(Request $request, $id)
    {
        $student = Student::findOrFail($id);
        $this->validate($request, [
            'nisn'              => 'required|numeric|min:10|unique:students,nisn,'. $id,
            'name'              => 'required|string',
            'gender'            => 'required|string',
            'place_of_birth'    => 'required|string',
            'date_of_birth'     => 'required|date',
            'address'           => 'required|string',
            'email'             => 'required|email',
            'npsn'              => 'required|string',
            'cv'                => 'nullable|mimes:doc,docx,pdf|max:1024',
            'photo'             => 'nullable|mimes:png,jpg,jpeg|max:1024',
        ]);

        $password = ($request->password != 'null') ? bcrypt($request->password) : $student->password ;
        $cv = $student->cv;
        $photo = $student->photo;
        if ($request->hasFile('cv')) {
            $fileCv = $request->file('cv');
            if ($cv != null) {
                unlink(storage_path('app/public/cv/').$cv);
            }
            $cv = rand().'.'.$fileCv->getClientOriginalExtension();
            $fileCv->storeAs('/public/cv',$cv);
            
        }
        if ($request->hasFile('photo')) {
            $filePhoto = $request->file('photo');
            if ($photo != null) {
                unlink(storage_path('app/public/photo/').$photo);
            }
            $photo = rand().'.'.$filePhoto->getClientOriginalExtension();
            $filePhoto->storeAs('/public/photo',$photo);
        }

        $student->update([
            'nisn'              => $request->nisn,
            'name'              => $request->name,
            'gender'            => $request->gender,
            'place_of_birth'    => $request->place_of_birth,
            'date_of_birth'     => $request->date_of_birth,
            'address'           => $request->address,
            'email'             => $request->email,
            'password'          => $password,
            'school_id'        => $request->npsn,
            'cv'                => $cv,
            'photo'             => $photo
        ]);

        return back()->with('message','Berhasil merubah data');

    }

    public function destroy($id)
    {
        $student = Student::findOrFail($id);
        unlink(storage_path('app/public/cv/').$student->cv);
        unlink(storage_path('app/public/photo/').$student->photo);
        $student->delete();
    }

}

resources/views/student/create.blade.php
@extends('layouts.admin.master')
@section('title','Tambah Alumni')
@section('css')
<link rel="stylesheet" href="{{ asset('select2/css/select2.min.css') }}">
@stop
@section('content') 
    <div class="row">
        <div class="col-md-6">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                  <h6 class="m-0 font-weight-bold text-primary"><a href="{{ route('alumni.index') }}" class="btn btn-circle"><i class="fa fa-arrow-left"></i></a> Data Pribadi</h6>
                </div>
                <div class="card-body">
                    @if (Session::has('message'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ Session::get('message') }}
                        @php 
                            Session::forget('message')
                        @endphp
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>                        
                    @endif
                    <form action="{{ route('alumni.store') }}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group row">
                           <div class="col-md-6 mb-3">
                                <label for="nisn">NISN</label>
                                <input type="text" class="form-control form-control-sm @error('nisn') is-invalid @enderror" name="nisn" value="{{ old('nisn') }}">
                                @error('nisn')
                                    <div class="invalid-feedback" role="alert">
                                        <span>{{ $message }}</span>
                                    </div>
                                @enderror
                           </div>
                           <div class="col-md-6 mb-3">
                                <label for="name">Nama</label>
                                <input type="text" class="form-control form-control-sm @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}">
                                @error('name')
                                    <div class="invalid-feedback" role="alert">
                                        <span>{{ $message }}</span>
                                    </div>
                                @enderror
                           </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-6">
                                <label for="gender">Jenis Kelamin</label>
                                <select name="gender" id="gender" class="form-control form-control-sm @error('gender') is-invalid @enderror">
                                    <option>Laki-laki</option>
                                    <option>Perempuan</option>
                                </select>
                            </div>
                            <div class="col-md-6">
                                <label for="email">Email</label>
                                <input type="text" class="form-control form-control-sm @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}">
                                @error('email')
                                    <div class="invalid-feedback" role="alert">
                                        <span>{{ $message }}</span>
                                    </div>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-6 mb-3">
                                <label for="place_of_birth">Tempat Lahir</label>
                                <input type="text" class="form-control form-control-sm @error('place_of_birth') is-invalid @enderror" name="place_of_birth" value="{{ old('place_of_birth') }}">
                                @error('place_of_birth')
                                    <div class="invalid-feedback" role="alert">
                                        <span>{{ $message }}</span>
                                    </div>
                                @enderror
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="date_of_birth">Tanggal Lahir</label>
                                <input type="date" class="form-control form-control-sm @error('date_of_birth') is-invalid @enderror" name="date_of_birth" value="{{ old('date_of_birth') }}">
                                @error('date_of_birth')
                                    <div class="invalid-feedback" role="alert">
                                        <span>{{ $message }}</span>
                                    </div>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="address">Alamat</label>
                            <textarea name="address" id="" cols="5" rows="5" class="form-control form-control-sm @error('address') is-invalid @enderror">{{ old('address') }}</textarea>
                            @error('address')
                                <div class="invalid-feedback" role="alert">
                                    <span>{{ $message }}</span>
                                </div>
                            @enderror
                        </div>
                    
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                  <h6 class="m-0 font-weight-bold text-primary">Data Sekolah</h6>
                </div>
                <div class="card-body">
                        <div class="form-group">
                            <label for="school_name">Nama Sekolah</label>
                            <select name="npsn" id="school_name" class="form-control" required style="width: 100%">
                                <option value="">Pilih Sekolah</option>
                                @if (auth()->user()->level == 0)
                                    @foreach ($sekolah as $item)
                                    <option value="{{ $item->id }}">{{ $item->sekolah }}</option>
                                @endforeach
                                @elseif(auth()->user()->level == 1)
                                    <option value="{{ auth()->user()->school_id }}" selected>{{ $getSekolah->sekolah->sekolah }}</option>
                                @endif
                            </select>
                        </div>
                        @if (auth()->user()->level == 1)
                            <hr>
                            <button class="btn btn-primary">Simpan</button>
                        @endif
                </div>
            </div>
            @if (auth()->user()->level == 0)
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                  <h6 class="m-0 font-weight-bold text-primary">Upload Form</h6>
                </div>
                <div class="card-body">
                        <div class="form-group">
                            <label for="photo">Foto</label>
                            <input type="file" name="photo" class="form-control @error('photo') is-invalid @enderror">
                            @error('photo')
                                <div class="invalid-feedback" role="alert">
                                    <span>{{ $message }}</span>
                                </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="cv">CV</label>
                            <input type="file" name="cv" class="form-control @error('cv') is-invalid @enderror">
                            @error('cv')
                                <div class="invalid-feedback" role="alert">
                                    <span>{{ $message }}</span>
                                </div>
                            @enderror
                        </div><hr>
                        <button class="btn btn-primary">Simpan</button>
                    </form>
                </div>
            </div>
            @endif
        </div>
    </div>
@endsection
@section('js')
<script src="{{ asset('select2/js/select2.min.js') }}"></script>
<script>
    $(document).ready(function(){
        $('#school_name').select2({
            width: 'resolve'
        });
    });
</script>
@stop

resources/views/student/index.blade.php
@extends('layouts.admin.master')
@section('title','Daftar Alumni')
@section('content')
<div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Daftar Alumni</h6>
    </div>
    <div class="card-body">
        <div class="mb-3">
            <a href="{{ route('alumni.create') }}" class="btn btn-success btn-sm">Tambah Data</a>
        </div>
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>NISN</th>
                        <th>Nama</th>
                        <th>Jenis Kelamin</th>
                        {{-- <th>Alamat</th> --}}
                        <th>Tempat, Tanggal Lahir</th>
                        <th>Sekolah</th>
                        <th>#</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($students as $student)
                        <tr>
                            <td>{{ $student->nisn }}</td>
                            <td>{{ $student->name }}</td>
                            <td>{{ $student->gender }}</td>
                            {{-- <td>{{ $student->address }}</td> --}}
                            <td>{{ $student->place_of_birth }}, {{ date('d-m-Y',strtotime($student->date_of_birth)) }}</td>
                                <td>{{ $student->sekolah->sekolah }}</td>
                            <td>
                                <button type="button" class="btn btn-primary btn-sm btn-circle" data-toggle="modal" data-target="#show{{ $student->id }}">
                                    <i class="fa fa-eye"></i>
                                </button>
                                <a href="{{ route('alumni.edit', $student->id) }}" class="btn btn-warning btn-sm btn-circle"><i class="fa fa-edit"></i></a>
                                <a href="{{ route('alumni.destroy', $student->id) }}" class="btn btn-danger btn-sm hapus btn-circle"><i class="fa fa-trash"></i></a>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="7">Tidak ada data</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
        {!! $students->links() !!}
    </div>
    <!-- Modal -->
    @foreach ($students as $item)
    <div class="modal fade" id="show{{ $item->id }}" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="staticBackdropLabel">{{ $item->name }}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-3 col-xs-12">
                        <img src="{{ asset('storage/photo/'.$item->photo) }}" alt="{{ $item->name }}" width="100" height="100">
                    </div>
                    <div class="col-md-9 col-xs-12">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <tr>
                                    <th>NISN</th>
                                    <td>:</td>
                                    <td>{{ $item->nisn }}</td>
                                </tr>
                                <tr>
                                    <th>Nama Alumni</th>
                                    <td>:</td>
                                    <td>{{ $item->name }}</td>
                                </tr>
                                <tr>
                                    <th>Jenis Kelamin</th>
                                    <td>:</td>
                                    <td>{{ $item->gender }}</td>
                                </tr>
                                <tr>
                                    <th>Tempat, Tanggal Lahir</th>
                                    <td>:</td>
                                    <td>{{ $item->place_of_birth }}, {{ $item->date_of_birth }}</td>
                                </tr>
                                <tr>
                                    <th>Alamat Alumni</th>
                                    <td>:</td>
                                    <td>{{ $item->address }}</td>
                                </tr>
                                <tr>
                                    <th>Email Alumni</th>
                                    <td>:</td>
                                    <td>{{ $item->email }}</td>
                                </tr>
                                <tr>
                                    <th>Alumni Sekolah</th>
                                    <td>:</td>
                                    <td>{{ $item->sekolah->sekolah }}</td>
                                </tr>
                                <tr>
                                    <th>Curiculum Vitae</th>
                                    <td>:</td>
                                    <td>
                                        @if (empty($item->cv))
                                            -
                                        @else
                                        <a href="{{ asset('storage/cv/'.$item->cv) }}" target="blank">Lihat disini</a>
                                        @endif
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            {{-- <button type="button" class="btn btn-primary">Understood</button> --}}
            </div>
        </div>
        </div>
    </div>
    @endforeach
</div>
@endsection
@section('js')
    <script src="{{ asset('vendor/sweetalert/sweetalert.min.js') }}"></script>
    <script>
        $(document).ready(function(){
            $('.hapus').on('click', function(){
                swal({
                    title: "Apa anda yakin?",
                    text: "Data yang dihapus tidak dapat dikembalikan",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true,
                })
                .then((willDelete) => {
                    if(willDelete) {
                        $.ajax({
                            url: $(this).attr('href'),
                            type: "DELETE",
                            data: {
                                "_token": "{{ csrf_token() }}"
                            },
                            success:function(){
                                swal("Data berhasil dihapus", {
                                    icon: "success",
                                }).then((willDelete) => {
                                    window.location="{{ route('alumni.index') }}"
                                });
                            }
                        });
                    } else {
                        swal("Data aman");
                    }
                });

                return false;
            });
        }); 
    </script>
@endsection