routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Whoops\Run;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/','FrontController@index');
Route::get('/daftar-sekolah','FrontController@daftarSekolah')->name('daftarsekolah');
Route::post('/daftar-sekolah','FrontController@storeDaftarSekolah')->name('daftarsekolah.store');
Route::get('/jobseeker/login','Jobseeker\LoginController@index')->name('login');
Route::post('/login/process','Jobseeker\LoginController@process')->name('login.process');
Route::post('/register','Jobseeker\RegisterController@register')->name('register');

Route::group(['prefix' => 'jobseeker', 'middleware' => 'students'], function(){
    Route::get('/jobvacancy','FrontController@jobVacancy')->name('jobvacancy');
    Route::get('/apply/{id}','FrontController@apply')->name('apply');
    Route::get('/informasi-lamaran','FrontController@informationApply')->name('informasi');
    Route::get('/profile','FrontController@profile')->name('profile.student');
    Route::post('/profile/{id}','FrontController@profileUpdate')->name('jobseeker.edit');
    Route::post('/logout','Jobseeker\LoginController@logout')->name('logout');
    Route::get('/postingan','FrontController@postingan')->name('postingan.index');
});

Route::group(['prefix' => 'admin'], function(){
    Route::get('/login','Auth\LoginController@loginAdmin')->name('login.admin');
    Route::post('/login','Auth\LoginController@loginProcessAdmin')->name('loginprocess.admin');
    Route::group(['middleware' => 'auth'], function(){
        Route::get('/dashboard','HomeController@index')->name('home.admin');
        Route::resource('company','CompanyController')->except(['show']);
        Route::resource('setting','SettingController')->except(['show']);
        Route::resource('alumni','StudentController')->except(['show']);
        Route::resource('admin','AdminController');
        Route::get('/adminsekolah/acc/{id}','AdminController@acc')->name('admin.acc');
        Route::get('/adminsekolah/reject/{id}','AdminController@reject')->name('admin.reject');
        Route::get('/adminsekolah/bukti/{id}','AdminController@bukti')->name('admin.bukti');
        Route::resource('bursakerja','JobVacancyController')->except(['show']);
        Route::get('/pelamar/{id}','JobVacancyController@pelamar')->name('pelamar');
        Route::post('/logout','Auth\LoginController@logout')->name('logout.admin');
        Route::get('/profile','HomeController@profile')->name('profile');
        Route::put('/profile/{id}','HomeController@profileUpdate')->name('profile.update');
        Route::get('/apply/accepted/{id}','JobVacancyController@accepted');
        Route::get('/apply/rejected/{id}','JobVacancyController@rejected');
        Route::post('/post','JobVacancyController@postStore')->name('post.store');
        Route::get('/apply/test/accpeted/{id}','JobVacancyController@testAccepted')->name('test.accepted');
        Route::get('/apply/test/rejected/{id}','JobVacancyController@testRejected')->name('test.rejected');
        Route::get('/apply/wawancara/accpeted/{id}','JobVacancyController@wawancaraAccepted')->name('wawancara.accepted');
        Route::get('/apply/wawancara/rejected/{id}','JobVacancyController@wawancaraRejected')->name('wawancara.rejected');
    } );
});

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    protected $guarded = [];

    public function jobVacancy()
    {
        return $this->hasMany(JobVacancy::class,'company_id');
    }

    public function post()
    {
        return $this->hasMany(Post::class,'company_id');
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Company;
use App\User;

class CompanyController extends Controller
{
    public function index()
    {
        if (auth()->user()->level == 1) {
            $id = auth()->user()->id;
            $companies = Company::where('user_id',$id)->orderBy('name','ASC')->paginate(10);
        }else{
            $companies = Company::orderBy('name','ASC')->paginate(10);
        }
        return view('company.index',compact('companies'));
    }

    public function create()
    {
        $sekolah = User::with('sekolah')->where('level',1)->get();

        // dd($sekolah);
        return view('company.create',compact('sekolah'));
    }

    public function store(Request $request)
    {
        $id = '';
        if ($request->exists('user_id')) {
            $id = $request->user_id;
        }else{
            $id = auth()->user()->id;
        }
        $this->validate($request, [
            'name'          => 'required|string',
            'address'       => 'required|string',
            'description'   => 'required|string'
        ]);

        Company::create([
            'name'          => $request->name,
            'address'       => $request->address,
            'description'   => $request->description,
            'user_id'       => $id
        ]);

        return back()->with('message','Berhasil menambahkan data');
    }

    public function edit($id)
    {
        $sekolah = User::with('sekolah')->where('level',1)->get();
        $company = Company::findOrFail($id);

        return view('company.edit',compact('company','sekolah'));
    }

    public function update(Request $request, $id)
    {
        $company = Company::findOrFail($id);
        $user_id = '';
        if ($request->exists('user_id')) {
            $user_id = $request->user_id;
        }else{
            $user_id = auth()->user()->id;
        }

        $this->validate($request, [
            'name'          => 'required|string',
            'address'       => 'required|string',
            'description'   => 'required|string'
        ]);

        $company->update([
            'name'          => $request->name,
            'address'       => $request->address,
            'description'   => $request->description,
            'user_id'       => $user_id
        ]);

        return back()->with('message','Berhasil merubah data');
    }

    public function destroy($id)
    {
        $company = Company::findOrFail($id);
        $company->delete();
    }
}

resources/views/company/create.blade.php
@extends('layouts.admin.master')
@section('title','Tambah Perusahaan')
@section('content')
    <div class="row">
        <div class="col-lg-8">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary"><a href="{{ route('company.index') }}" class="btn btn-circle"><i class="fa fa-arrow-left"></i></a>  Tambah Perusahaan</h6>
                </div>
                <div class="card-body">
                    @if (Session::has('message'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ Session::get('message') }}
                        @php 
                            Session::forget('message')
                        @endphp
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>                        
                    @endif
                    <form action="{{ route('company.store') }}" method="post">
                        @csrf
                        <div class="form-group">
                            <label for="name">Nama Perusahaan</label>
                            <input type="text" name="name" id="name" class="form-control @error('name') is-invalid @enderror" value="{{ old('name') }}">
                            @error('name')
                                <div class="invalid-feedback" role="alert">
                                    <span>{{ $message }}</span>
                                </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="address">Alamat Perusahaan</label>
                            <input type="text" name="address" id="address" class="form-control @error('address') is-invalid @enderror" value="{{ old('address') }}">
                            @error('address')
                                <div class="invalid-feedback" role="alert">
                                    <span>{{ $message }}</span>
                                </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="description">Deskripsi Perusahaan</label>
                            <textarea name="description" id="description" cols="5" rows="5" class="form-control @error('description') is-invalid @enderror ">{{ old('description') }}</textarea>
                            @error('description')
                                <div class="invalid-feedback" role="alert">
                                    <span>{{ $message }}</span>
                                </div>
                            @enderror
                        </div>
                        @if (auth()->user()->level == 0)
                        <div class="form-group">
                            <label for="">Lowongan Untuk</label>
                            <select name="user_id" id="" class="form-control" required>
                                <option value="">Pilih Sekolah</option>
                                @foreach ($sekolah as $item)
                                    <option value="{{ $item->id }}">{{ $item->sekolah->sekolah }}</option>
                                @endforeach
                            </select>
                        </div>
                        @endif
                        <button class="btn btn-primary">Simpan</button>
                    </form>
                </div>
              </div>
        </div>
    </div>
@endsection

resources/views/company/edit.blade.php
@extends('layouts.admin.master')
@section('title', $company->name)
@section('content')
    <div class="row">
        <div class="col-lg-8">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary"><a href="{{ route('company.index') }}" class="btn btn-circle"><i class="fa fa-arrow-left"></i></a>  {{ $company->name }}</h6>
                </div>
                <div class="card-body">
                    @if (Session::has('message'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ Session::get('message') }}
                        @php 
                            Session::forget('message')
                        @endphp
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>                        
                    @endif
                    <form action="{{ route('company.update', $company->id) }}" method="post">
                        @csrf
                        @method('put')
                        <div class="form-group">
                            <label for="name">Nama Perusahaan</label>
                            <input type="text" name="name" id="name" class="form-control @error('name') is-invalid @enderror" value="{{ $company->name }}">
                            @error('name')
                                <div class="invalid-feedback" role="alert">
                                    <span>{{ $message }}</span>
                                </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="address">Alamat Perusahaan</label>
                            <input type="text" name="address" id="address" class="form-control @error('address') is-invalid @enderror" value="{{ $company->address }}">
                            @error('address')
                                <div class="invalid-feedback" role="alert">
                                    <span>{{ $message }}</span>
                                </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="description">Deskripsi Perusahaan</label>
                            <textarea name="description" id="description" cols="5" rows="5" class="form-control @error('description') is-invalid @enderror ">{{ $company->description }}</textarea>
                            @error('description')
                                <div class="invalid-feedback" role="alert">
                                    <span>{{ $message }}</span>
                                </div>
                            @enderror
                        </div>
                        @if (auth()->user()->level == 0)
                        <div class="form-group">
                            <label for="">Lowongan Untuk</label>
                            <select name="user_id" id="" class="form-control" required>
                                <option value="">Pilih Sekolah</option>
                                @foreach ($sekolah as $item)
                                    <option value="{{ $item->id }}" {{ $company->user_id == $item->id ? 'selected' : '' }}>{{ $item->sekolah->sekolah }}</option>
                                @endforeach
                            </select>
                        </div>
                        @endif
                        <button class="btn btn-primary">Simpan</button>
                    </form>
                </div>
              </div>
        </div>
    </div>
@endsection

resources/views/company/index.blade.php
@extends('layouts.admin.master')
@section('title','Daftar Perusahaan')
@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Daftar Perusahaan</h6>
                </div>
                <div class="card-body">
                    <div class="mb-3">
                        <a href="{{ route('company.create') }}" class="btn btn-sm btn-success">Tambah Data</a>
                    </div>
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>Nama Perusahaan</th>
                                    <th>Alamat Perusahaan</th>
                                    <th>Deskripsi Perusahaan</th>
                                    <th>#</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($companies as $item)
                                    <tr>
                                        <td>{{ $item->name }}</td>
                                        <td>{{ $item->address }}</td>
                                        <td>{{ $item->description }}</td>
                                        <td>
                                            <a href="{{ route('company.edit',$item->id) }}" class="btn btn-warning btn-sm btn-circle"><i class="fa fa-edit"></i></a>
                                            <a href="{{ route('company.destroy',$item->id) }}" class="btn btn-danger btn-sm btn-circle hapus"><i class="fa fa-trash"></i></a>
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="4">Tidak ada data</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>

                    {!! $companies->links() !!}
                </div>
            </div>
        </div>
    </div>
@endsection
@section('js')
    <script src="{{ asset('vendor/sweetalert/sweetalert.min.js') }}"></script>
    <script>
        $(document).ready(function(){
            $('.hapus').on('click', function(){
                swal({
                    title: "Apa anda yakin?",
                    text: "Data yang dihapus tidak dapat dikembalikan",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true,
                })
                .then((willDelete) => {
                    if(willDelete) {
                        $.ajax({
                            url: $(this).attr('href'),
                            type: "DELETE",
                            data: {
                                "_token": "{{ csrf_token() }}"
                            },
                            success:function(){
                                swal("Data berhasil dihapus", {
                                    icon: "success",
                                }).then((willDelete) => {
                                    window.location="{{ route('company.index') }}"
                                });
                            }
                        });
                    } else {
                        swal("Data aman");
                    }
                });

                return false;
            });
        }); 
    </script>
@endsection