routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Whoops\Run;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/','FrontController@index');
Route::get('/daftar-sekolah','FrontController@daftarSekolah')->name('daftarsekolah');
Route::post('/daftar-sekolah','FrontController@storeDaftarSekolah')->name('daftarsekolah.store');
Route::get('/jobseeker/login','Jobseeker\LoginController@index')->name('login');
Route::post('/login/process','Jobseeker\LoginController@process')->name('login.process');
Route::post('/register','Jobseeker\RegisterController@register')->name('register');

Route::group(['prefix' => 'jobseeker', 'middleware' => 'students'], function(){
    Route::get('/jobvacancy','FrontController@jobVacancy')->name('jobvacancy');
    Route::get('/apply/{id}','FrontController@apply')->name('apply');
    Route::get('/informasi-lamaran','FrontController@informationApply')->name('informasi');
    Route::get('/profile','FrontController@profile')->name('profile.student');
    Route::post('/profile/{id}','FrontController@profileUpdate')->name('jobseeker.edit');
    Route::post('/logout','Jobseeker\LoginController@logout')->name('logout');
    Route::get('/postingan','FrontController@postingan')->name('postingan.index');
});

Route::group(['prefix' => 'admin'], function(){
    Route::get('/login','Auth\LoginController@loginAdmin')->name('login.admin');
    Route::post('/login','Auth\LoginController@loginProcessAdmin')->name('loginprocess.admin');
    Route::group(['middleware' => 'auth'], function(){
        Route::get('/dashboard','HomeController@index')->name('home.admin');
        Route::resource('company','CompanyController')->except(['show']);
        Route::resource('setting','SettingController')->except(['show']);
        Route::resource('alumni','StudentController')->except(['show']);
        Route::resource('admin','AdminController');
        Route::get('/adminsekolah/acc/{id}','AdminController@acc')->name('admin.acc');
        Route::get('/adminsekolah/reject/{id}','AdminController@reject')->name('admin.reject');
        Route::get('/adminsekolah/bukti/{id}','AdminController@bukti')->name('admin.bukti');
        Route::resource('bursakerja','JobVacancyController')->except(['show']);
        Route::get('/pelamar/{id}','JobVacancyController@pelamar')->name('pelamar');
        Route::post('/logout','Auth\LoginController@logout')->name('logout.admin');
        Route::get('/profile','HomeController@profile')->name('profile');
        Route::put('/profile/{id}','HomeController@profileUpdate')->name('profile.update');
        Route::get('/apply/accepted/{id}','JobVacancyController@accepted');
        Route::get('/apply/rejected/{id}','JobVacancyController@rejected');
        Route::post('/post','JobVacancyController@postStore')->name('post.store');
        Route::get('/apply/test/accpeted/{id}','JobVacancyController@testAccepted')->name('test.accepted');
        Route::get('/apply/test/rejected/{id}','JobVacancyController@testRejected')->name('test.rejected');
        Route::get('/apply/wawancara/accpeted/{id}','JobVacancyController@wawancaraAccepted')->name('wawancara.accepted');
        Route::get('/apply/wawancara/rejected/{id}','JobVacancyController@wawancaraRejected')->name('wawancara.rejected');
    } );
});

app/JobVacancy.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class JobVacancy extends Model
{
    protected $guarded = [];

    public function company()
    {
        return $this->belongsTo(Company::class);
    }

    public function apply()
    {
        return $this->hasMany(Apply::class,'id');
    }
}

app/Http/Controllers/JobVacancyController.php
<?php

namespace App\Http\Controllers;

use App\Apply;
use Illuminate\Http\Request;
use App\JobVacancy;
use App\Company;
use App\Post;
use App\User;

class JobVacancyController extends Controller
{
    public function index()
    {
        $job_vacancies = JobVacancy::with('company');

        // if (auth()->user()->level == 0) {
            $job_vacancies = $job_vacancies->where('user_id', auth()->user()->id );
        // }

        $job_vacancies = $job_vacancies->orderBy('created_at','DESC')->paginate(10);

        // return response()->json($job_vacancies);
        return view('jobvacancy.index',compact('job_vacancies'));
    }

    public function create()
    {
        $company = Company::get();
        $user = User::with('sekolah')->where('level',1)->get();
        return view('jobvacancy.create',compact('company','user'));
    }

    public function store(Request $request)
    {
        $arr = $this->validate($request, [
            'company_id'        => 'required|exists:companies,id',
            'user_id'           => 'required|exists:users,id',
            'title'             => 'required|string',
            'end_date'          => 'required|date',
            'start_salary'      => 'required|numeric',
            'end_salary'        => 'required|numeric',
            'description'       => 'required|string',
            'position'          => 'required|string',
            'location'          => 'required|string'
        ]);

        // dd($arr);

        JobVacancy::create([
            'company_id'        => $request->company_id,
            'user_id'           => $request->user_id,
            'title'             => $request->title,
            'end_date'          => $request->end_date,
            'start_salary'      => $request->start_salary,
            'end_salary'        => $request->end_salary,
            'description'       => $request->description,
            'position'          => $request->position,
            'location'          => $request->location,
            'school_id'         => auth()->user()->school_id
        ]);

        return back()->with('message','Berhasil menambahkan data');
    }

    public function edit($id)
    {
        $company = Company::get();
        $job_vacancy = JobVacancy::findOrFail($id);
        return view('jobvacancy.edit',compact('company','job_vacancy'));
    }

    public function update(Request $request, $id)
    {
        $job_vacancy = JobVacancy::findOrFail($id);

        $arr = $this->validate($request, [
            'company_id'        => 'required|exists:companies,id',
            'title'             => 'required|string',
            'end_date'          => 'required|date',
            'start_salary'      => 'required|numeric',
            'end_salary'        => 'required|numeric',
            'description'       => 'required|string',
            'position'          => 'required|string',
            'location'          => 'required|string'
        ]);

        $job_vacancy->update([
            'company_id'        => $request->company_id,
            'title'             => $request->title,
            'end_date'          => $request->end_date,
            'start_salary'      => $request->start_salary,
            'end_salary'        => $request->end_salary,
            'description'       => $request->description,
            'position'          => $request->position,
            'location'          => $request->location
        ]);

        return back()->with('message','Berhasil merubah data');

    }

    public function destroy($id)
    {
        $job_vacancy = JobVacancy::findOrFail($id);
        $job_vacancy->delete();
    }

    public function pelamar($id)
    {
        $pelamar_proses = Apply::with(['student.sekolah','jobvacancy'])->where('job_vacancy_id',$id)->where('status','Diproses')->orWhere('status','Tidak Lolos')->paginate(10);

        $pelamar_test = Apply::with(['student.sekolah','jobvacancy'])->where('job_vacancy_id',$id)->where('status','Test')->orWhere('status','Tidak Lolos')->paginate(10);

        $pelamar_wawancara = Apply::with(['student.sekolah','jobvacancy'])->where('job_vacancy_id',$id)->where('status','Wawancara')->orWhere('status','Tidak Lolos')->orWhere('status','selesai')->paginate(10);
        $perusahaan = JobVacancy::with('company')->findOrFail($id);

        // dd($perusahaan);

        return view('pelamar',compact('pelamar_proses','pelamar_test','pelamar_wawancara','perusahaan'));
    }

    public function accepted($id)
    {
        $apply = Apply::findOrFail($id);
        $apply->update([
            'status'    => 'Test',
            'color_status' => 'badge badge-info'
        ]);

        return back()->with('message','Berhasil');
    }
    public function rejected($id)
    {
        $apply = Apply::findOrFail($id);
        $apply->update([
            'status'    => 'Tidak Lolos',
            'color_status' => 'badge badge-danger'
        ]);

        return back()->with('message','Berhasil');
    }
    
    public function postStore(Request $request)
    {
        Post::create([
            'title'   => $request->title,
            'description'   => $request->description,
            'company_id'    => $request->perusahaan_id,
            'user_id'       => $request->user_id
        ]);

        return back()->with('message','Post Berhasil');
    }

    public function testAccepted($id)
    {
        $apply = Apply::findOrFail($id);
        $apply->update([
            'status'    => 'Wawancara',
            'color_status' => 'badge badge-success'
        ]);

        return back()->with('message','Berhasil');
    }
    public function testRejected($id)
    {
        $apply = Apply::findOrFail($id);
        $apply->update([
            'status'    => 'Tidak Lolos',
            'color_status' => 'badge badge-danger'
        ]);

        return back()->with('message','Berhasil');
    }
    public function wawancaraAccepted($id)
    {
        $apply = Apply::findOrFail($id);
        $apply->update([
            'status'    => 'selesai',
            'color_status' => 'badge badge-success'
        ]);

        return back()->with('message','Berhasil');
    }
    public function wawancaraRejected($id)
    {
        $apply = Apply::findOrFail($id);
        $apply->update([
            'status'    => 'Tidak Lolos',
            'color_status' => 'badge badge-danger'
        ]);

        return back()->with('message','Berhasil');
    }
}

resources/views/jobvacancy/create.blade.php
@extends('layouts.admin.master')
@section('title','Tambah Bursa Kerja')
@section('css')
<link rel="stylesheet" href="{{ asset('select2/css/select2.min.css') }}">
@stop
@section('content')
<div class="row">
    <div class="col-md-8">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Tambah Bursa Kerja</h6>
            </div>
            <div class="card-body">
                @if (Session::has('message'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ Session::get('message') }}
                        @php 
                            Session::forget('message')
                        @endphp
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>                        
                    @endif
                <form action="{{ route('bursakerja.store') }}" method="post">
                    @csrf
                    <div class="form-group row">
                        <div class="col-md-6 mb-3">
                            <label for="company_id">Perusahaan</label>
                            <select name="company_id" id="company_id" class="form-control form-control-sm @error('company_id') is-invalid @enderror">
                                @foreach ($company as $item)
                                    <option value="{{ $item->id }}">{{ $item->name }}</option>
                                @endforeach
                            </select>
                            @error('company_id')
                                <div class="invalid-feedback" role="alert">
                                    <span>{{ $message }}</span>
                                </div>
                            @enderror
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="title">Judul</label>
                            <input type="text" name="title" class="form-control form-control-sm @error('title') is-invalid @enderror" value="{{ old('title') }}">
                            @error('title')
                                <div class="invalid-feedback" role="alert">
                                    <span>{{ $message }}</span>
                                </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-12 mb-3">
                            <label for="description">Deskripsi</label>
                            <textarea name="description" id="description" cols="5" rows="5" class="form-control form-control-sm">{{ old('description') }}</textarea>
                            @error('description')
                                <div class="invalid-feedback" role="alert">
                                    <span>{{ $message }}</span>
                                </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                       
                            
                            @if (auth()->user()->level == 0)
                            <div class="col-md-4 mb-3">
                                <label for="school">Sekolah</label>
                                <select name="user_id" id="school_id" class="form-control form-control-sm @error('school_id') is-invalid @enderror">
                                    <option value="0">Pilih Sekolah</option>
                                    @foreach ($user as $item)
                                        <option value="{{ $item->id }}">{{ $item->sekolah->sekolah }}</option>
                                    @endforeach
                                </select>
                                @error('company_id')
                                    <div class="invalid-feedback" role="alert">
                                        <span>{{ $message }}</span>
                                    </div>
                                @enderror
                            </div>
                            @else
                                <input type="hidden" name="user_id" value="{{ auth()->user()->id }}">
                            @endif

                        <div class="col-md-4 mb-3">
                            <label for="start_salary">Gaji Mulai</label>
                            <input type="text" name="start_salary" class="form-control form-control-sm @error('start_salary') is-invalid @enderror" value="{{ old('start_salary') }}">
                            @error('start_salary')
                                <div class="invalid-feedback" role="alert">
                                    <span>{{ $message }}</span>
                                </div>
                            @enderror
                        </div>
                        <div class="col-md-4 mb-3">
                            <label for="end_salary">Gaji Sampai</label>
                            <input type="text" name="end_salary" class="form-control form-control-sm @error('end_salary') is-invalid @enderror" value="{{ old('end_salary') }}">
                            @error('end_salary')
                                <div class="invalid-feedback" role="alert">
                                    <span>{{ $message }}</span>
                                </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-4 mb-3">
                            <label for="position">Posisi</label>
                            <input type="text" name="position" class="form-control form-control-sm @error('position') is-invalid @enderror" value="{{ old('position') }}">
                            @error('position')
                                <div class="invalid-feedback" role="alert">
                                    <span>{{ $message }}</span>
                                </div>
                            @enderror
                        </div>
                        <div class="col-md-4 mb-3">
                            <label for="location">Lokasi</label>
                            <input type="text" name="location" class="form-control form-control-sm @error('location') is-invalid @enderror" value="{{ old('location') }}">
                            @error('location')
                                <div class="invalid-feedback" role="alert">
                                    <span>{{ $message }}</span>
                                </div>
                            @enderror
                        </div>
                        <div class="col-md-4 mb-3">
                            <label for="end_date">Batas Waktu</label>
                            <input type="date" name="end_date" class="form-control form-control-sm @error('end_date') is-invalid @enderror" value="{{ old('end_date') }}">
                            @error('location')
                                <div class="invalid-feedback" role="alert">
                                    <span>{{ $message }}</span>
                                </div>
                            @enderror
                        </div>
                    </div>
                    <button class="btn btn-sm btn-primary">Simpan</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection
@section('js')
<script src="{{ asset('select2/js/select2.min.js') }}"></script>
<script>
    $(document).ready(function(){
        $('#school_id').select2({
            width: 'resolve'
        });
    });
</script>
@stop

resources/views/jobvacancy/edit.blade.php
@extends('layouts.admin.master')
@section('title',$job_vacancy->title)
@section('content')
<div class="row">
    <div class="col-md-8">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Ubah Bursa Kerja</h6>
            </div>
            <div class="card-body">
                @if (Session::has('message'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ Session::get('message') }}
                        @php 
                            Session::forget('message')
                        @endphp
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>                        
                    @endif
                <form action="{{ route('bursakerja.update', $job_vacancy->id) }}" method="post">
                    @csrf
                    @method('put')
                    <div class="form-group row">
                        <div class="col-md-6 mb-3">
                            <label for="company_id">Perusahaan</label>
                            <select name="company_id" id="company_id" class="form-control form-control-sm @error('company_id') is-invalid @enderror">
                                @foreach ($company as $item)
                                    <option value="{{ $item->id }}" {{ $job_vacancy->company_id == $item->id ? 'selected' : '' }}>{{ $item->name }}</option>
                                @endforeach
                            </select>
                            @error('company_id')
                                <div class="invalid-feedback" role="alert">
                                    <span>{{ $message }}</span>
                                </div>
                            @enderror
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="title">Judul</label>
                            <input type="text" name="title" class="form-control form-control-sm @error('title') is-invalid @enderror" value="{{ $job_vacancy->title }}">
                            @error('title')
                                <div class="invalid-feedback" role="alert">
                                    <span>{{ $message }}</span>
                                </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-12 mb-3">
                            <label for="description">Deskripsi</label>
                            <textarea name="description" id="description" cols="5" rows="5" class="form-control form-control-sm">{{ $job_vacancy->description }}</textarea>
                            @error('description')
                                <div class="invalid-feedback" role="alert">
                                    <span>{{ $message }}</span>
                                </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-6 mb-3">
                            <label for="start_salary">Gaji Mulai</label>
                            <input type="text" name="start_salary" class="form-control form-control-sm @error('start_salary') is-invalid @enderror" value="{{ $job_vacancy->start_salary }}">
                            @error('start_salary')
                                <div class="invalid-feedback" role="alert">
                                    <span>{{ $message }}</span>
                                </div>
                            @enderror
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="end_salary">Gaji Sampai</label>
                            <input type="text" name="end_salary" class="form-control form-control-sm @error('end_salary') is-invalid @enderror" value="{{$job_vacancy->end_salary }}">
                            @error('end_salary')
                                <div class="invalid-feedback" role="alert">
                                    <span>{{ $message }}</span>
                                </div>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-4 mb-3">
                            <label for="position">Posisi</label>
                            <input type="text" name="position" class="form-control form-control-sm @error('position') is-invalid @enderror" value="{{ $job_vacancy->position }}">
                            @error('position')
                                <div class="invalid-feedback" role="alert">
                                    <span>{{ $message }}</span>
                                </div>
                            @enderror
                        </div>
                        <div class="col-md-4 mb-3">
                            <label for="location">Lokasi</label>
                            <input type="text" name="location" class="form-control form-control-sm @error('location') is-invalid @enderror" value="{{ $job_vacancy->location }}">
                            @error('location')
                                <div class="invalid-feedback" role="alert">
                                    <span>{{ $message }}</span>
                                </div>
                            @enderror
                        </div>
                        <div class="col-md-4 mb-3">
                            <label for="end_date">Batas Waktu</label>
                            <input type="date" name="end_date" class="form-control form-control-sm @error('end_date') is-invalid @enderror" value="{{ $job_vacancy->end_date }}">
                            @error('location')
                                <div class="invalid-feedback" role="alert">
                                    <span>{{ $message }}</span>
                                </div>
                            @enderror
                        </div>
                    </div>
                    <button class="btn btn-sm btn-primary">Simpan</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/jobvacancy/index.blade.php
@extends('layouts.admin.master')
@section('title','Bursa Kerja')
@section('content')
<div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Bursa Kerja</h6>
    </div>
    <div class="card-body">
        <div class="mb-3">
            <a href="{{ route('bursakerja.create') }}" class="btn btn-sm btn-success">Tambah Data</a>
        </div>
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Perusahaan</th>
                        <th>Judul</th>
                        <th>Tanggal Berakhir</th>
                        <th>#</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($job_vacancies as $item)
                        <tr>
                            <td>{{ $item->company->name }}</td>
                            <td>{{ $item->title }}</td>
                            <td>{{ date('d F Y',strtotime($item->end_date)) }}</td>
                            <td>
                                <a href="{{ route('pelamar',$item->id) }}" class="btn btn-success btn-sm btn-circle"><i class="fa fa-users"></i></a>
                                <button type="button" class="btn btn-primary btn-sm btn-circle" data-toggle="modal" data-target="#show{{ $item->id }}">
                                    <i class="fa fa-eye"></i>
                                </button>
                                <a href="{{ route('bursakerja.edit', $item->id) }}" class="btn btn-warning btn-sm btn-circle"><i class="fa fa-edit"></i></a>
                                <a href="{{ route('bursakerja.destroy', $item->id) }}" class="btn btn-danger btn-sm hapus btn-circle"><i class="fa fa-trash"></i></a>
                            </td>
                        </tr>
                    @empty
                        
                    @endforelse
                </tbody>
            </table>
        </div>
        {!! $job_vacancies->links() !!}
    </div>
</div>
<!-- Modal -->
@foreach ($job_vacancies as $job)
    

<div class="modal fade" id="show{{ $job->id }}" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">{{ $job->company->name }}</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <h5><b>{{ $job->title }}</b></h5>
            <small>Dibuat pada {{ date('d F Y', strtotime($job->created_at)) }}</small>
            <p>Range Gaji Rp.{{ number_format($job->start_salary) }} - Rp.{{ number_format($job->end_salary) }} <br> {{ $job->position }} <br> {{ $job->location }}</p>
            <hr>
            <p>{{ $job->description }}</p>
            <hr>
            <p>Closed <strong>{{ date('d F Y', strtotime($job->end_date)) }}</strong></p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          
        </div>
      </div>
    </div>
  </div>
@endforeach
@endsection
@section('js')
    <script src="{{ asset('vendor/sweetalert/sweetalert.min.js') }}"></script>
    <script>
        $(document).ready(function(){
            $('.hapus').on('click', function(){
                swal({
                    title: "Apa anda yakin?",
                    text: "Data yang dihapus tidak dapat dikembalikan",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true,
                })
                .then((willDelete) => {
                    if(willDelete) {
                        $.ajax({
                            url: $(this).attr('href'),
                            type: "DELETE",
                            data: {
                                "_token": "{{ csrf_token() }}"
                            },
                            success:function(){
                                swal("Data berhasil dihapus", {
                                    icon: "success",
                                }).then((willDelete) => {
                                    window.location="{{ route('bursakerja.index') }}"
                                });
                            }
                        });
                    } else {
                        swal("Data aman");
                    }
                });

                return false;
            });
        }); 
    </script>
@endsection